from enum import Enum

class ResponseSignal(Enum):


    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    PROCESSING_FAILED = "FILE_PROCESS_FAILED"
    PROCESSING_SUCCESS = "FILE_PROCESS_SUCCESS"
    NO_FILES_TO_PROCESS = "NO_FILES_TO_PROCESS"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    INSERT_INTO_VECTOREDB_FAILED = "INSERT_INTO_VECTORDB_FAILED"
    INSERT_INTO_VECTOREDB_SUCCESS = "INSERT_INTO_VECTORDB_SUCCESS"
    VECTORDB_COLLECTION_RETRIVED="VECTORDB_COLLECTION_RETRIVED"
    VECTORDB_SEARCH_SUCCESS="VECTORDB_SEARCH_SUCCESS"
    VECTORDB_SEARCH_FAILED="VECTORDB_SEARCH_FAILED"


